### ISSUE TITLE
Setup and Run Project Environment on Workspace (Again) to Ensure No New Issues - For Peer-testing #2

### ISSUE THREAD

**Issue by Radhi1017** [muizzyusuf/ethics-dashboard-2#173]
make sure everything is up and running before the second peer-testing sessions

**Comment by mogden8** [comment]
Completed! Almost forgot to run migrations but everything went perfectly.

**Comment by Radhi1017** [comment]
Completed! had some issues again after doing that during today's session, but it seemed to work
