### ISSUE TITLE
Create CourseSelect Branch and Merge into Main

### ISSUE THREAD

**Issue by mogden8** [muizzyusuf/ethics-dashboard-2#40]
With Changes to Course Create ID and formatting

**Comment by mogden8** [comment]
CourseSelect/Create Branch Created, Muizz will review and merge later.

**Comment by muizzyusuf** [comment]
modified the migrations to enable grades & comments be nullable on ethical issues, stakeholder section and utilitarianism section. modified the home page and course create to include modals so now it's all on one page. included the edit course and delete course functions. Changed the course route into a resource in web.php and created the necessary functions in the course controller (we've already used delete, store & update). Added in the input for roles into the user tables migration and created the functionality for it in the register page
